services:
  # 1. Base de Datos del Sistema
  db:
    image: postgres:18.1-alpine
    container_name: translator_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - translator-network

  # 2. Backend
  backend:
    build: ./backend
    container_name: translator_backend
    restart: on-failure
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app  # Hot-reload en desarrollo
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - translator-network

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: translator_frontend
    # Comando para Hot-reload en desarrollo
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que se sobrescriban los módulos del container
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - translator-network

volumes:
  postgres_data:

networks:
  translator-network:
    driver: bridge