"""create_query_history_table

Revision ID: 81d716f0ad7f
Revises: 3271964aeb4c
Create Date: 2026-02-09 05:40:24.935165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "81d716f0ad7f"
down_revision: Union[str, Sequence[str], None] = "3271964aeb4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_history",
        sa.Column("query_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column("sql_query", sa.Text(), nullable=False),
        sa.Column("cypher_query", sa.Text(), nullable=True),
        sa.Column(
            "query_status",
            sa.Enum("PENDING", "TRANSLATED", "EXECUTED", "FAILED", name="querystatus"),
            nullable=False,
        ),
        sa.Column(
            "failure_stage",
            sa.Enum("TRANSLATION", "EXECUTION", name="failurestage"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("translation_time", sa.Float(), nullable=True),
        sa.Column("execution_time", sa.Float(), nullable=True),
        sa.Column("result_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.connection_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("query_id"),
    )
    op.create_index(
        op.f("ix_query_history_query_id"), "query_history", ["query_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_history_query_id"), table_name="query_history")
    op.drop_table("query_history")
    # ### end Alembic commands ###
