"""update_query_history_table

Revision ID: a6cc5685060b
Revises: 81d716f0ad7f
Create Date: 2026-02-09 12:44:14.762925

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6cc5685060b"
down_revision: Union[str, Sequence[str], None] = "81d716f0ad7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("query_history_connection_id_fkey"), "query_history", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("query_history_user_id_fkey"), "query_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "query_history", "users", ["user_id"], ["user_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "query_history",
        "connections",
        ["connection_id"],
        ["connection_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "query_history", type_="foreignkey")
    op.drop_constraint(None, "query_history", type_="foreignkey")
    op.create_foreign_key(
        op.f("query_history_user_id_fkey"),
        "query_history",
        "users",
        ["user_id"],
        ["user_id"],
    )
    op.create_foreign_key(
        op.f("query_history_connection_id_fkey"),
        "query_history",
        "connections",
        ["connection_id"],
        ["connection_id"],
    )
    # ### end Alembic commands ###
